name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['**/*.py', '**/*.yml'] # only run workflow when source or config files changed
  pull_request:
    branches: [main]
    paths: ['**/*.py', '**/*.yml']

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Run Tests
        run: python -m pytest --durations 0
        env:
          ILOVEPDF_PUBLIC_KEY: ${{ secrets.ILOVEPDF_PUBLIC_KEY }}
